export const testimonials = [
  { id: 1, text: "I tried not to like it. It didn't help.", author: "Reluctant User" },
  { id: 2, text: "So much scroll, I forgot what I was looking for.", author: "Lost Browser" },
  { id: 3, text: "Design you can't ignore. I tried.", author: "Witness #42" },
  { id: 4, text: "My thumb filed a complaint.", author: "Ergonomics Dept." },
  { id: 5, text: "Too many opinions. Not enough scroll.", author: "Comment Section" },
  { id: 6, text: "I scrolled for answers and found attitude.", author: "Seeker" },
  { id: 7, text: "Good design shouldn't beg. This does.", author: "Critic #7" },
  { id: 8, text: "It looked at me first.", author: "Eyewitness" },
  { id: 9, text: "The UI started a small riot in my tabs.", author: "Tab Hoarder" },
  { id: 10, text: "Scrolling is the new breathing.", author: "Optimist" },
  { id: 11, text: "White space louder than black noise.", author: "Minimalist Dropout" },
  { id: 12, text: "It feels like a Poltergeist touched my screen.", author: "Occult Witness" },
  { id: 13, text: "Fashion that bleeds into interface.", author: "Archivist" },
  { id: 14, text: "My laptop fan joined the protest.", author: "Heatwave" },
  { id: 15, text: "This isn't responsive. It's rebellious.", author: "UX Rebel" },
  { id: 16, text: "Every scroll felt like backstage noise.", author: "Sound Tech" },
  { id: 17, text: "I clicked and it stared back.", author: "Haunted Tester" },
  { id: 18, text: "It consumes like the Consumed collection.", author: "Raf Devotee" },
  { id: 19, text: "This page has more layers than Virginia Creeper.", author: "Botanist" },
  { id: 20, text: "Typography screamed louder than copy.", author: "Silent Reader" },
  { id: 21, text: "Feels like a zine stapled to my retinas.", author: "DIY Printer" },
  { id: 22, text: "Nothing aligned, everything aligned.", author: "Grid Skeptic" },
  { id: 23, text: "My scroll wheel disintegrated.", author: "Hardware Victim" },
  { id: 24, text: "It didn't ask for permission. Neither did I.", author: "Uninvited Guest" },
  { id: 25, text: "A riot in Helvetica.", author: "Typo Anarchist" },
  { id: 26, text: "Feels like backstage chaos coded in React.", author: "Stagehand" },
  { id: 27, text: "Every pixel felt like torn fabric.", author: "Tailor Ghost" },
  { id: 28, text: "Was this designed or summoned?", author: "Occult Designer" },
  { id: 29, text: "My cache revolted and cleared itself.", author: "Browser Historian" },
  { id: 30, text: "Navigation is a rumor here.", author: "Lost Guide" },
  { id: 31, text: "Poltergeist of design touched my cursor.", author: "Medium" },
  { id: 32, text: "So raw it cut my resolution.", author: "Graphic Fatalist" },
  { id: 33, text: "The shadows read like footnotes.", author: "Critical Theorist" },
  { id: 34, text: "Too fast for nostalgia, too slow for clarity.", author: "Time Traveler" },
  { id: 35, text: "The hover states feel like threats.", author: "Nervous Tester" },
  { id: 36, text: "If code could riot, this would be it.", author: "Syntax Punk" },
  { id: 37, text: "An interface dressed in confessionals.", author: "Black Confessor" },
  { id: 38, text: "The scroll felt staged, like runway pacing.", author: "Front Row Seat" },
  { id: 39, text: "Raf would approve. My boss wouldn't.", author: "Intern" },
  { id: 40, text: "It glitched like memory on fire.", author: "Burnt Archive" },
]
